### ISSUE TITLE
Repository not get clone from jitpack

### ISSUE THREAD

**Issue by parmeetmaster** [Edsuns/AdblockAndroid#1]
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.Edsuns.AdblockAndroid:ad-filter:1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/Edsuns/AdblockAndroid/ad-filter/1.0/ad-filter-1.0.pom
       - https://repo.maven.apache.org/maven2/com/github/Edsuns/AdblockAndroid/ad-filter/1.0/ad-filter-1.0.pom
       - https://jitpack.io/com/github/Edsuns/AdblockAndroid/ad-filter/1.0/ad-filter-1.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/Edsuns/AdblockAndroid/ad-filter/1.0/ad-filter-1.0.pom
     Required by:
         project :app

* Try:

**Comment by Edsuns** [comment]
You need to modify the version to the latest one (0.9.1). Version 1.0 not released yet.

**Comment by parmeetmaster** [comment]
can you upload one more sample with Gradle 7.2, There are a lot of issues raised when I do development. Webview listener class is also missing in the library.

**Comment by Edsuns** [comment]
> can you upload one more sample with Gradle 7.2, There are a lot of issues raised when I do development. Webview listener class is also missing in the library.

You can fork this project and make the modification.

**Comment by parmeetmaster** [comment]
Actually in the new Android studio chipmunk is unable to get modules via import. Otherwise, the dependency problems do not get raised.

I already tried everything but failed to generate a working sample. Can I share my repository please check if you can help?
![image](https://user-images.githubusercontent.com/42370506/168411150-9af11558-89be-48aa-86b2-74fe1a76c8bc.png)

**Comment by parmeetmaster** [comment]
One more error comes 
`Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.github.Edsuns.AdblockAndroid:ad-filter:0.9.1.`

**Comment by jonathanshannaro** [comment]
> Actually in the new Android studio chipmunk is unable to get modules via import. Otherwise, the dependency problems do not get raised.
> 
> I already tried everything but failed to generate a working sample. Can I share my repository please check if you can help? ![image](https://user-images.githubusercontent.com/42370506/168411150-9af11558-89be-48aa-86b2-74fe1a76c8bc.png)

Your problem solved sir?

**Comment by Edsuns** [comment]
I'm busy recently. Welcome to make a PR to fix it.

**Comment by parmeetmaster** [comment]
Hello is this issue is fixed

**Comment by Reezlaw** [comment]
The README still says to use v1.0, it still doesn't resolve. Someone should update it and advise to put v0.9.1 in dependencies
